name: pokedex_clean_architecture
description: A simple Pokedex app using Dio and clean architecture.

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.1.2
  flutter_hooks: ^0.21.2
  hooks_riverpod: ^2.3.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  cached_network_image: ^3.3.1
  lottie: ^3.3.1
  flutter_riverpod: ^2.6.1
  firebase_performance: ^0.10.1+7
  firebase_core: ^3.14.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  freezed: ^2.3.2
  json_serializable: ^6.7.0
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/animations/pokeball_lottie.json
    - assets/animations/pokeball.gif
    - assets/images/pokeball.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  remove_alpha_ios: true
