// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4l8pp580JhiD0vPK3bzVWp6_KnxbMu8g',
    appId: '1:578787971708:web:e0cacba036b06ed6f2aff9',
    messagingSenderId: '578787971708',
    projectId: 'pokedex-d058d',
    authDomain: 'pokedex-d058d.firebaseapp.com',
    storageBucket: 'pokedex-d058d.firebasestorage.app',
    measurementId: 'G-YXMMTTZ8ZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7sFdKGQIc1tfphUpep6s4wPVqhoAAwwU',
    appId: '1:578787971708:android:efe34d0ec02c520ff2aff9',
    messagingSenderId: '578787971708',
    projectId: 'pokedex-d058d',
    storageBucket: 'pokedex-d058d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbKsB0sNftrfYIebUh0VMVSEJ6C0DxIqk',
    appId: '1:578787971708:ios:5ea9f175d1bdb67ff2aff9',
    messagingSenderId: '578787971708',
    projectId: 'pokedex-d058d',
    storageBucket: 'pokedex-d058d.firebasestorage.app',
    iosBundleId: 'com.example.pokedexCleanArchitecture',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbKsB0sNftrfYIebUh0VMVSEJ6C0DxIqk',
    appId: '1:578787971708:ios:5ea9f175d1bdb67ff2aff9',
    messagingSenderId: '578787971708',
    projectId: 'pokedex-d058d',
    storageBucket: 'pokedex-d058d.firebasestorage.app',
    iosBundleId: 'com.example.pokedexCleanArchitecture',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4l8pp580JhiD0vPK3bzVWp6_KnxbMu8g',
    appId: '1:578787971708:web:9eb65d32391f1e1af2aff9',
    messagingSenderId: '578787971708',
    projectId: 'pokedex-d058d',
    authDomain: 'pokedex-d058d.firebaseapp.com',
    storageBucket: 'pokedex-d058d.firebasestorage.app',
    measurementId: 'G-87N0P5H01H',
  );
}
